// Mock data for Reddy Infra procurement app

export interface Category {
  id: string;
  name: string;
  icon: string;
  productCount: number;
  image: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  image: string;
  retailPrice: number;
  pooledPrice: number;
  unit: string;
  moq: number;
  currentPoolQty: number;
  targetPoolQty: number;
  specs: Record<string, string>;
  emiAvailable: boolean;
  deliveryDays: number;
}

export interface Order {
  id: string;
  items: Array<{
    product: Product;
    quantity: number;
  }>;
  status: 'pooled' | 'confirmed' | 'dispatched' | 'delivered';
  createdAt: Date;
  dispatchDate: Date;
  deliveryDate: Date;
  total: number;
  poolSavings: number;
}

export interface EducationCard {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: 'cement',
    name: 'Cement',
    icon: 'building-2',
    productCount: 8,
    image: '/cement.jpg',
  },
  {
    id: 'steel',
    name: 'Steel',
    icon: 'layers',
    productCount: 8,
    image: '/steel.jpg',
  },
  {
    id: 'electrical',
    name: 'Electrical',
    icon: 'zap',
    productCount: 8,
    image: '/electrical.jpg',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    icon: 'droplets',
    productCount: 8,
    image: '/plumbing.jpg',
  },
  {
    id: 'hardware',
    name: 'Hardware',
    icon: 'wrench',
    productCount: 8,
    image: '/hardware.jpg',
  },
];

export const products: Product[] = [
  // CEMENT PRODUCTS
  {
    id: 'cement-001',
    name: 'UltraTech PPC Cement',
    brand: 'UltraTech',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=400',
    retailPrice: 420,
    pooledPrice: 365,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 2450,
    targetPoolQty: 5000,
    specs: {
      'Type': 'Portland Pozzolana Cement',
      'Grade': '53 Grade',
      'Weight': '50 kg',
      'Setting Time': '30 mins initial',
      'Compressive Strength': '53 MPa at 28 days',
    },
    emiAvailable: true,
    deliveryDays: 7,
  },
  {
    id: 'cement-002',
    name: 'ACC Gold Cement',
    brand: 'ACC',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?w=400',
    retailPrice: 435,
    pooledPrice: 378,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 1800,
    targetPoolQty: 5000,
    specs: {
      'Type': 'OPC Cement',
      'Grade': '53 Grade',
      'Weight': '50 kg',
      'Setting Time': '28 mins initial',
      'Compressive Strength': '53 MPa at 28 days',
    },
    emiAvailable: true,
    deliveryDays: 7,
  },
  {
    id: 'cement-003',
    name: 'Ambuja Plus Cement',
    brand: 'Ambuja',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 410,
    pooledPrice: 355,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 3200,
    targetPoolQty: 5000,
    specs: {
      'Type': 'Portland Pozzolana Cement',
      'Grade': '53 Grade',
      'Weight': '50 kg',
      'Setting Time': '32 mins initial',
      'Compressive Strength': '53 MPa at 28 days',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'cement-004',
    name: 'Birla A1 Cement',
    brand: 'Birla',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1541123603104-512919d6a96c?w=400',
    retailPrice: 395,
    pooledPrice: 342,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 4100,
    targetPoolQty: 5000,
    specs: {
      'Type': 'OPC Cement',
      'Grade': '43 Grade',
      'Weight': '50 kg',
      'Setting Time': '35 mins initial',
      'Compressive Strength': '43 MPa at 28 days',
    },
    emiAvailable: false,
    deliveryDays: 6,
  },
  {
    id: 'cement-005',
    name: 'Dalmia DSP Cement',
    brand: 'Dalmia',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 405,
    pooledPrice: 350,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 2900,
    targetPoolQty: 5000,
    specs: {
      'Type': 'Slag Cement',
      'Grade': '53 Grade',
      'Weight': '50 kg',
      'Setting Time': '30 mins initial',
      'Compressive Strength': '53 MPa at 28 days',
    },
    emiAvailable: true,
    deliveryDays: 8,
  },
  {
    id: 'cement-006',
    name: 'Shree Ultra Cement',
    brand: 'Shree',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1517089596392-fb9a9033e05b?w=400',
    retailPrice: 385,
    pooledPrice: 335,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 3800,
    targetPoolQty: 5000,
    specs: {
      'Type': 'Portland Pozzolana Cement',
      'Grade': '43 Grade',
      'Weight': '50 kg',
      'Setting Time': '32 mins initial',
      'Compressive Strength': '43 MPa at 28 days',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'cement-007',
    name: 'JK White Cement',
    brand: 'JK Cement',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=400',
    retailPrice: 850,
    pooledPrice: 745,
    unit: 'bag (40kg)',
    moq: 50,
    currentPoolQty: 850,
    targetPoolQty: 2000,
    specs: {
      'Type': 'White Portland Cement',
      'Grade': '53 Grade',
      'Weight': '40 kg',
      'Setting Time': '45 mins initial',
      'Whiteness': '87%+',
    },
    emiAvailable: true,
    deliveryDays: 10,
  },
  {
    id: 'cement-008',
    name: 'Ramco Supercem',
    brand: 'Ramco',
    category: 'cement',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 398,
    pooledPrice: 345,
    unit: 'bag (50kg)',
    moq: 100,
    currentPoolQty: 2100,
    targetPoolQty: 5000,
    specs: {
      'Type': 'Portland Pozzolana Cement',
      'Grade': '53 Grade',
      'Weight': '50 kg',
      'Setting Time': '28 mins initial',
      'Compressive Strength': '53 MPa at 28 days',
    },
    emiAvailable: false,
    deliveryDays: 6,
  },
  
  // STEEL PRODUCTS
  {
    id: 'steel-001',
    name: 'Tata Tiscon TMT Bar',
    brand: 'Tata Steel',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1567361808960-dec9cb578182?w=400',
    retailPrice: 72500,
    pooledPrice: 65800,
    unit: 'tonne',
    moq: 5,
    currentPoolQty: 35,
    targetPoolQty: 100,
    specs: {
      'Grade': 'Fe 500D',
      'Diameter': '8mm, 10mm, 12mm, 16mm, 20mm',
      'Length': '12m standard',
      'Rib Pattern': 'Parallel rib pattern',
      'Elongation': '>16%',
    },
    emiAvailable: true,
    deliveryDays: 10,
  },
  {
    id: 'steel-002',
    name: 'JSW NeoSteel TMT',
    brand: 'JSW Steel',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400',
    retailPrice: 71000,
    pooledPrice: 64200,
    unit: 'tonne',
    moq: 5,
    currentPoolQty: 48,
    targetPoolQty: 100,
    specs: {
      'Grade': 'Fe 550D',
      'Diameter': '8mm, 10mm, 12mm, 16mm, 20mm, 25mm',
      'Length': '12m standard',
      'Corrosion Resistance': 'CRS Technology',
      'Elongation': '>14.5%',
    },
    emiAvailable: true,
    deliveryDays: 10,
  },
  {
    id: 'steel-003',
    name: 'SAIL TMT Rebar',
    brand: 'SAIL',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 68000,
    pooledPrice: 61500,
    unit: 'tonne',
    moq: 5,
    currentPoolQty: 62,
    targetPoolQty: 100,
    specs: {
      'Grade': 'Fe 500',
      'Diameter': '8mm, 10mm, 12mm, 16mm',
      'Length': '12m standard',
      'Surface': 'Ribbed',
      'Elongation': '>16%',
    },
    emiAvailable: true,
    deliveryDays: 12,
  },
  {
    id: 'steel-004',
    name: 'Vizag Steel TMT',
    brand: 'Vizag Steel',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1567361808960-dec9cb578182?w=400',
    retailPrice: 67500,
    pooledPrice: 60800,
    unit: 'tonne',
    moq: 5,
    currentPoolQty: 75,
    targetPoolQty: 100,
    specs: {
      'Grade': 'Fe 500D',
      'Diameter': '8mm, 10mm, 12mm, 16mm, 20mm',
      'Length': '12m standard',
      'BIS Standard': 'IS 1786:2008',
      'Elongation': '>16%',
    },
    emiAvailable: false,
    deliveryDays: 8,
  },
  {
    id: 'steel-005',
    name: 'Kamdhenu Saria',
    brand: 'Kamdhenu',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400',
    retailPrice: 66000,
    pooledPrice: 59500,
    unit: 'tonne',
    moq: 5,
    currentPoolQty: 55,
    targetPoolQty: 100,
    specs: {
      'Grade': 'Fe 500D',
      'Diameter': '8mm, 10mm, 12mm, 16mm',
      'Length': '12m standard',
      'Bend Test': '4D',
      'Elongation': '>16%',
    },
    emiAvailable: true,
    deliveryDays: 9,
  },
  {
    id: 'steel-006',
    name: 'Steel Angle 50x50',
    brand: 'Jindal Steel',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 58000,
    pooledPrice: 52500,
    unit: 'tonne',
    moq: 2,
    currentPoolQty: 18,
    targetPoolQty: 50,
    specs: {
      'Type': 'Equal Angle',
      'Size': '50mm x 50mm x 5mm',
      'Length': '6m standard',
      'Grade': 'IS 2062 E250',
      'Surface': 'Mill Finish',
    },
    emiAvailable: false,
    deliveryDays: 7,
  },
  {
    id: 'steel-007',
    name: 'MS Channel 100mm',
    brand: 'SAIL',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1567361808960-dec9cb578182?w=400',
    retailPrice: 62000,
    pooledPrice: 56000,
    unit: 'tonne',
    moq: 2,
    currentPoolQty: 22,
    targetPoolQty: 50,
    specs: {
      'Type': 'C Channel',
      'Size': 'ISMC 100',
      'Length': '6m standard',
      'Grade': 'IS 2062 E250',
      'Weight': '9.56 kg/m',
    },
    emiAvailable: true,
    deliveryDays: 10,
  },
  {
    id: 'steel-008',
    name: 'GI Wire 2.5mm',
    brand: 'Tata Wiron',
    category: 'steel',
    image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400',
    retailPrice: 95,
    pooledPrice: 82,
    unit: 'kg',
    moq: 500,
    currentPoolQty: 3500,
    targetPoolQty: 10000,
    specs: {
      'Type': 'Galvanized Iron Wire',
      'Diameter': '2.5mm',
      'Coating': 'Hot Dip Galvanized',
      'Tensile Strength': '350-500 MPa',
      'Packing': '25 kg coil',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  
  // ELECTRICAL PRODUCTS
  {
    id: 'electrical-001',
    name: 'Havells Lifeline Plus Wire',
    brand: 'Havells',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
    retailPrice: 4850,
    pooledPrice: 4280,
    unit: 'coil (90m)',
    moq: 20,
    currentPoolQty: 180,
    targetPoolQty: 500,
    specs: {
      'Size': '2.5 sq mm',
      'Conductor': 'Electrolytic Grade Copper',
      'Insulation': 'FR PVC',
      'Voltage Grade': '1100V',
      'Length': '90 meters',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'electrical-002',
    name: 'Polycab FR Wire 4mm',
    brand: 'Polycab',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 7200,
    pooledPrice: 6380,
    unit: 'coil (90m)',
    moq: 20,
    currentPoolQty: 245,
    targetPoolQty: 500,
    specs: {
      'Size': '4 sq mm',
      'Conductor': 'Electrolytic Grade Copper',
      'Insulation': 'FR PVC',
      'Voltage Grade': '1100V',
      'Length': '90 meters',
    },
    emiAvailable: true,
    deliveryDays: 5,
  },
  {
    id: 'electrical-003',
    name: 'Anchor Advance MCB',
    brand: 'Anchor',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
    retailPrice: 385,
    pooledPrice: 328,
    unit: 'piece',
    moq: 50,
    currentPoolQty: 380,
    targetPoolQty: 1000,
    specs: {
      'Type': 'Single Pole MCB',
      'Rating': '16A',
      'Breaking Capacity': '10kA',
      'Curve': 'C Type',
      'Standard': 'IS 8828',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'electrical-004',
    name: 'Legrand Modular Switch',
    brand: 'Legrand',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 85,
    pooledPrice: 72,
    unit: 'piece',
    moq: 100,
    currentPoolQty: 720,
    targetPoolQty: 2000,
    specs: {
      'Type': '1 Way Switch',
      'Rating': '16A 250V',
      'Module': '1M',
      'Finish': 'White',
      'Warranty': '2 years',
    },
    emiAvailable: false,
    deliveryDays: 3,
  },
  {
    id: 'electrical-005',
    name: 'Finolex Power Cable',
    brand: 'Finolex',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
    retailPrice: 12500,
    pooledPrice: 10800,
    unit: 'coil (100m)',
    moq: 10,
    currentPoolQty: 85,
    targetPoolQty: 200,
    specs: {
      'Type': 'Armoured Cable',
      'Size': '3 Core x 2.5 sq mm',
      'Insulation': 'PVC',
      'Armour': 'Steel Wire',
      'Voltage': 'Up to 1100V',
    },
    emiAvailable: true,
    deliveryDays: 7,
  },
  {
    id: 'electrical-006',
    name: 'Havells DB Box 8 Way',
    brand: 'Havells',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 1450,
    pooledPrice: 1250,
    unit: 'piece',
    moq: 25,
    currentPoolQty: 165,
    targetPoolQty: 500,
    specs: {
      'Type': 'Distribution Board',
      'Ways': '8 Way SPN',
      'Material': 'MS Sheet',
      'Protection': 'IP43',
      'Color': 'RAL 7035 Grey',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'electrical-007',
    name: 'GM Modular Socket',
    brand: 'GM',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
    retailPrice: 145,
    pooledPrice: 118,
    unit: 'piece',
    moq: 100,
    currentPoolQty: 580,
    targetPoolQty: 1500,
    specs: {
      'Type': '3 Pin Socket',
      'Rating': '16A 250V',
      'Module': '2M',
      'Shutter': 'Safety Shutter',
      'Standard': 'IS 1293',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'electrical-008',
    name: 'Philips LED Downlight',
    brand: 'Philips',
    category: 'electrical',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 420,
    pooledPrice: 355,
    unit: 'piece',
    moq: 50,
    currentPoolQty: 420,
    targetPoolQty: 1000,
    specs: {
      'Wattage': '12W',
      'Lumens': '1200 lm',
      'Color Temp': '6500K Cool White',
      'Cut-out': '150mm',
      'Life': '25000 hours',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  
  // PLUMBING PRODUCTS
  {
    id: 'plumbing-001',
    name: 'Ashirvad CPVC Pipes',
    brand: 'Ashirvad',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    retailPrice: 285,
    pooledPrice: 248,
    unit: 'pipe (3m)',
    moq: 100,
    currentPoolQty: 650,
    targetPoolQty: 1000,
    specs: {
      'Size': '1 inch (25mm)',
      'Material': 'CPVC',
      'Length': '3 meters',
      'Pressure Rating': 'SDR 11',
      'Temperature': 'Up to 93°C',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'plumbing-002',
    name: 'Supreme PVC Pipe',
    brand: 'Supreme',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
    retailPrice: 185,
    pooledPrice: 158,
    unit: 'pipe (3m)',
    moq: 100,
    currentPoolQty: 780,
    targetPoolQty: 1500,
    specs: {
      'Size': '1 inch (25mm)',
      'Material': 'uPVC',
      'Length': '3 meters',
      'Pressure Rating': '6 kg/cm²',
      'Application': 'Cold Water',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'plumbing-003',
    name: 'Astral CPVC Elbow',
    brand: 'Astral',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    retailPrice: 28,
    pooledPrice: 22,
    unit: 'piece',
    moq: 500,
    currentPoolQty: 3200,
    targetPoolQty: 5000,
    specs: {
      'Size': '25mm x 90°',
      'Material': 'CPVC',
      'Type': 'Elbow',
      'Thread': 'Plain',
      'Standard': 'IS 15778',
    },
    emiAvailable: false,
    deliveryDays: 3,
  },
  {
    id: 'plumbing-004',
    name: 'Parryware Angle Cock',
    brand: 'Parryware',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
    retailPrice: 650,
    pooledPrice: 545,
    unit: 'piece',
    moq: 50,
    currentPoolQty: 285,
    targetPoolQty: 500,
    specs: {
      'Type': 'Angle Cock',
      'Material': 'Brass',
      'Size': '15mm',
      'Finish': 'Chrome Plated',
      'Warranty': '5 years',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'plumbing-005',
    name: 'Hindware Concealed Cistern',
    brand: 'Hindware',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    retailPrice: 4800,
    pooledPrice: 4150,
    unit: 'piece',
    moq: 20,
    currentPoolQty: 125,
    targetPoolQty: 300,
    specs: {
      'Type': 'Dual Flush',
      'Capacity': '6/3 Liters',
      'Material': 'ABS Plastic',
      'Installation': 'Concealed',
      'Warranty': '10 years',
    },
    emiAvailable: true,
    deliveryDays: 7,
  },
  {
    id: 'plumbing-006',
    name: 'Jaquar Pillar Cock',
    brand: 'Jaquar',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
    retailPrice: 1250,
    pooledPrice: 1050,
    unit: 'piece',
    moq: 30,
    currentPoolQty: 185,
    targetPoolQty: 400,
    specs: {
      'Type': 'Pillar Cock',
      'Material': 'Brass',
      'Finish': 'Chrome',
      'Spout Type': 'Fixed',
      'Warranty': '7 years',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'plumbing-007',
    name: 'Prince SWR Pipe 4"',
    brand: 'Prince',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    retailPrice: 420,
    pooledPrice: 365,
    unit: 'pipe (3m)',
    moq: 50,
    currentPoolQty: 320,
    targetPoolQty: 500,
    specs: {
      'Size': '110mm (4 inch)',
      'Material': 'PVC',
      'Length': '3 meters',
      'Type': 'SWR (Soil Waste Rain)',
      'Color': 'Grey',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'plumbing-008',
    name: 'Essco Health Faucet',
    brand: 'Essco',
    category: 'plumbing',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
    retailPrice: 850,
    pooledPrice: 720,
    unit: 'piece',
    moq: 50,
    currentPoolQty: 340,
    targetPoolQty: 600,
    specs: {
      'Type': 'Health Faucet Set',
      'Material': 'ABS + Brass',
      'Hose Length': '1m',
      'Finish': 'Chrome',
      'Warranty': '3 years',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  
  // HARDWARE PRODUCTS
  {
    id: 'hardware-001',
    name: 'Godrej Navtal Lock Set',
    brand: 'Godrej',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 1850,
    pooledPrice: 1620,
    unit: 'set',
    moq: 50,
    currentPoolQty: 320,
    targetPoolQty: 500,
    specs: {
      'Type': 'Cylindrical Lock',
      'Material': 'Brass + Stainless Steel',
      'Keys': '3 keys included',
      'Finish': 'Satin Nickel',
      'Warranty': '7 years',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'hardware-002',
    name: 'Dorset Door Closer',
    brand: 'Dorset',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 1450,
    pooledPrice: 1250,
    unit: 'piece',
    moq: 30,
    currentPoolQty: 185,
    targetPoolQty: 400,
    specs: {
      'Type': 'Hydraulic Door Closer',
      'Capacity': '60-85 kg door',
      'Adjustable': 'Speed & Latching',
      'Material': 'Aluminum Alloy',
      'Standard': 'EN 1154',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
  {
    id: 'hardware-003',
    name: 'Ebco Tower Bolt 8"',
    brand: 'Ebco',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 185,
    pooledPrice: 155,
    unit: 'piece',
    moq: 100,
    currentPoolQty: 580,
    targetPoolQty: 1000,
    specs: {
      'Type': 'Tower Bolt',
      'Size': '8 inch (200mm)',
      'Material': 'Stainless Steel SS304',
      'Finish': 'Satin',
      'Application': 'Doors/Windows',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'hardware-004',
    name: 'Stanley Door Hinge 4"',
    brand: 'Stanley',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 320,
    pooledPrice: 275,
    unit: 'pair',
    moq: 100,
    currentPoolQty: 620,
    targetPoolQty: 1000,
    specs: {
      'Type': 'Ball Bearing Hinge',
      'Size': '4" x 3" x 3mm',
      'Material': 'Stainless Steel SS304',
      'Finish': 'Satin',
      'Load Capacity': '40 kg per hinge',
    },
    emiAvailable: false,
    deliveryDays: 4,
  },
  {
    id: 'hardware-005',
    name: 'Ozone Glass Door Lock',
    brand: 'Ozone',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 2850,
    pooledPrice: 2450,
    unit: 'set',
    moq: 20,
    currentPoolQty: 125,
    targetPoolQty: 300,
    specs: {
      'Type': 'Glass Door Lock',
      'Glass Thickness': '10-12mm',
      'Material': 'Stainless Steel + Zinc',
      'Keys': '3 computerized keys',
      'Warranty': '5 years',
    },
    emiAvailable: true,
    deliveryDays: 6,
  },
  {
    id: 'hardware-006',
    name: 'Kich Cabinet Handle',
    brand: 'Kich',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 85,
    pooledPrice: 68,
    unit: 'piece',
    moq: 200,
    currentPoolQty: 1250,
    targetPoolQty: 2000,
    specs: {
      'Type': 'D Handle',
      'Size': '128mm CC',
      'Material': 'Zinc Alloy',
      'Finish': 'Brush Nickel',
      'Application': 'Cabinet/Drawer',
    },
    emiAvailable: false,
    deliveryDays: 3,
  },
  {
    id: 'hardware-007',
    name: 'Ipsa Sliding Door Kit',
    brand: 'Ipsa',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    retailPrice: 3500,
    pooledPrice: 2980,
    unit: 'set',
    moq: 15,
    currentPoolQty: 85,
    targetPoolQty: 200,
    specs: {
      'Type': 'Soft Close Sliding System',
      'Door Weight': 'Up to 100 kg',
      'Track Length': '2m',
      'Material': 'Aluminum + Steel',
      'Warranty': '5 years',
    },
    emiAvailable: true,
    deliveryDays: 7,
  },
  {
    id: 'hardware-008',
    name: 'Hettich Drawer Channel',
    brand: 'Hettich',
    category: 'hardware',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    retailPrice: 450,
    pooledPrice: 385,
    unit: 'pair',
    moq: 50,
    currentPoolQty: 380,
    targetPoolQty: 600,
    specs: {
      'Type': 'Ball Bearing Channel',
      'Size': '450mm (18 inch)',
      'Load': '35 kg',
      'Extension': 'Full Extension',
      'Warranty': '10 years',
    },
    emiAvailable: false,
    deliveryDays: 5,
  },
];

export const educationCards: EducationCard[] = [
  {
    id: 'pooling',
    title: 'Why Pool Orders?',
    description: 'Aggregating orders across buyers gives you factory-direct pricing. More volume = lower costs for everyone.',
    icon: 'users',
  },
  {
    id: 'logistics',
    title: 'Logistics Savings',
    description: 'Coordinated dispatch reduces per-unit freight costs by up to 40%. Scheduled deliveries mean predictable timelines.',
    icon: 'truck',
  },
  {
    id: 'timing',
    title: 'Strategic Timing',
    description: 'Our dispatch cycles are timed with market fluctuations. Patience often means 10-15% additional savings.',
    icon: 'clock',
  },
];

export const cities = [
  'Hyderabad',
  'Bengaluru',
  'Chennai',
  'Mumbai',
  'Pune',
  'Ahmedabad',
  'Delhi NCR',
  'Kolkata',
  'Jaipur',
  'Lucknow',
];

export const userTypes = [
  { id: 'contractor', label: 'Contractor', description: 'Building projects for clients' },
  { id: 'builder', label: 'Builder / Developer', description: 'Real estate development' },
  { id: 'retailer', label: 'Material Retailer', description: 'Selling construction materials' },
  { id: 'architect', label: 'Architect / Engineer', description: 'Design and planning' },
  { id: 'individual', label: 'Individual Buyer', description: 'Personal construction needs' },
];

// Calculate next dispatch date (every Monday and Thursday)
export function getNextDispatchDate(): Date {
  const now = new Date();
  const day = now.getDay();
  let daysUntilDispatch: number;

  if (day < 1) {
    daysUntilDispatch = 1; // Sunday -> Monday
  } else if (day < 4) {
    daysUntilDispatch = 4 - day; // Mon-Wed -> Thursday
  } else if (day === 4) {
    daysUntilDispatch = 4; // Thursday -> Next Monday
  } else {
    daysUntilDispatch = 8 - day; // Fri-Sat -> Next Monday
  }

  const dispatchDate = new Date(now);
  dispatchDate.setDate(dispatchDate.getDate() + daysUntilDispatch);
  dispatchDate.setHours(10, 0, 0, 0);
  return dispatchDate;
}

export function getDaysUntilDispatch(): number {
  const now = new Date();
  const dispatch = getNextDispatchDate();
  const diffTime = dispatch.getTime() - now.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

export function getHoursUntilDispatch(): number {
  const now = new Date();
  const dispatch = getNextDispatchDate();
  const diffTime = dispatch.getTime() - now.getTime();
  return Math.floor(diffTime / (1000 * 60 * 60));
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.category === categoryId);
}

export const mockOrders: Order[] = [
  {
    id: 'ORD-2024-001',
    items: [
      { product: products[0], quantity: 200 },
      { product: products[8], quantity: 10 },
    ],
    status: 'dispatched',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    dispatchDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    deliveryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    total: 730000,
    poolSavings: 85000,
  },
  {
    id: 'ORD-2024-002',
    items: [
      { product: products[1], quantity: 150 },
    ],
    status: 'pooled',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    dispatchDate: getNextDispatchDate(),
    deliveryDate: new Date(getNextDispatchDate().getTime() + 7 * 24 * 60 * 60 * 1000),
    total: 56700,
    poolSavings: 8550,
  },
  {
    id: 'ORD-2024-003',
    items: [
      { product: products[16], quantity: 50 },
      { product: products[24], quantity: 200 },
    ],
    status: 'delivered',
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    dispatchDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    deliveryDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    total: 263600,
    poolSavings: 35900,
  },
];

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

export function calculateSavings(retailPrice: number, pooledPrice: number): number {
  return Math.round(((retailPrice - pooledPrice) / retailPrice) * 100);
}
